# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/84308/Desktop/my_CortexM3_hdmi/vivado/CortexM3.srcs/sources_1/ip/video_clk/video_clk.xci
# IP: The module: 'video_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84308/Desktop/my_CortexM3_hdmi/vivado/CortexM3.srcs/sources_1/ip/video_clk/video_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84308/Desktop/my_CortexM3_hdmi/vivado/CortexM3.srcs/sources_1/ip/video_clk/video_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84308/Desktop/my_CortexM3_hdmi/vivado/CortexM3.srcs/sources_1/ip/video_clk/video_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/84308/Desktop/my_CortexM3_hdmi/vivado/CortexM3.srcs/sources_1/ip/video_clk/video_clk.xci
# IP: The module: 'video_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84308/Desktop/my_CortexM3_hdmi/vivado/CortexM3.srcs/sources_1/ip/video_clk/video_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84308/Desktop/my_CortexM3_hdmi/vivado/CortexM3.srcs/sources_1/ip/video_clk/video_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84308/Desktop/my_CortexM3_hdmi/vivado/CortexM3.srcs/sources_1/ip/video_clk/video_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
