# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.cache/wt [current_project]
set_property parent.project_path C:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBArbiterM0.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBArbiterM1.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBArbiterM2.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBDecoderS0.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBDecoderS1.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBDecoderS2.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBInputstg.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBMatrix.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBMatrix_default_slave.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBOutputStgM0.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBOutputStgM1.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/ahb/L1_AHBMatrix/L1_AHBOutputStgM2.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/hdmi/asyn_rst_syn.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/ov5640/cmos_capture_data.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/apb/cmsdk_ahb_to_apb.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/sram/cmsdk_ahb_to_sram.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/led/cmsdk_apb3_eg_slave_interface_led.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/led/cmsdk_apb3_eg_slave_led.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/bus/apb/cmsdk_apb_slave_mux.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/uart/cmsdk_apb_uart.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/sram/cmsdk_fpga_sram.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/core/cortexm3ds_logic.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/button/custom_apb_button.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/hdmi/custom_apb_hdmi.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/led/custom_apb_led.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/ddr3/ddr3_fifo_ctrl.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/ddr3/ddr3_rw.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/ddr3/ddr3_top.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/hdmi/dvi_encoder.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/hdmi/dvi_transmitter_top.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/hdmi/hdmi_top.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/ov5640/i2c_dri.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/ov5640/i2c_ov5640_rgb565_cfg.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/ov5640/ov5640_dri.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/ov5640_hdmi.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/vip/rgb2ycbcr.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/hdmi/serializer_10_to_1.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/hdmi/video_driver.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/vip/vip.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/peripheral/vip/vip/ycbcr2bin.v
  C:/Users/84308/Desktop/my_CortexM3/my_rtl/CortexM3.v
}
read_ip -quiet c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]

read_ip -quiet c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/wr_fifo/wr_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/wr_fifo/wr_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/wr_fifo/wr_fifo_clocks.xdc]

read_ip -quiet c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/rd_fifo/rd_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/rd_fifo/rd_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/rd_fifo/rd_fifo_clocks.xdc]

read_ip -quiet c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84308/Desktop/my_CortexM3/vivado_a7/CortexM3.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/84308/Desktop/my_CortexM3/xdc/CortexM3_a7.xdc
set_property used_in_implementation false [get_files C:/Users/84308/Desktop/my_CortexM3/xdc/CortexM3_a7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CortexM3 -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CortexM3.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CortexM3_utilization_synth.rpt -pb CortexM3_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
